// Generated by CoffeeScript 1.8.0
var capitalize, toString, types, wassat;

toString = Object.prototype.toString;

capitalize = function(str) {
  return str[0].toUpperCase() + str.slice(1);
};

types = {
  "[object String]": "string",
  "[object Number]": "number",
  "[object Boolean]": "boolean",
  "[object Object]": "object",
  "[object Array]": "array",
  "[object Function]": "function",
  "[object RegExp]": "regexp",
  "[object Date]": "date",
  "[object Arguments]": "arguments",
  "[object Undefined]": "undefined",
  "null": "null"
};

wassat = function(obj) {
  if (obj === null) {
    return "null";
  }
  return types[toString.call(obj)];
};

Object.keys(types).forEach(function(key) {
  var fnName, type;
  type = types[key];
  fnName = "is" + capitalize(type);
  fnName = fnName === "isRegexp" ? "isRegExp" : fnName;
  return wassat[fnName] = function(obj) {
    return wassat(obj) === type;
  };
});

wassat.isNothing = function(obj) {
  var result;
  result = wassat(obj);
  return result === "null" || result === "undefined";
};

module.exports = wassat;
